FRONTEND: cleanup filenames and constants, add jest setup
MetLifeLegalPlans/portunus pull request #203
Opened 2020-09-21 21:06 UTC by swang192

2020-09-22 18:30 UTC, Ian-MacLeod reviewed
Looks good

2020-09-22 18:30 UTC, Ian-MacLeod commented on frontend/jest.config.js
> +// For a detailed explanation regarding each configuration property, visit:
Do we want to keep all the commented out settings in this file?

2020-09-22 18:30 UTC, Ian-MacLeod commented on frontend/jest.setup.js
> +  nextRouter.useRouter = () => window.mockedRouter;
I'm sure that there must be a better way to make these objects available during tests than attaching them to the window, but I don't know what that is offhand. I suppose I'm ok with this for now, but we should look for a nicer solution.

2020-10-01 21:22 UTC, markrawls requested changes

2020-10-01 21:22 UTC, markrawls commented on frontend/components/Nav.js
> +import { SUPPORT_PHONE_NUMBER } from '@@/utils/constants';
The '@@/' is no longer necessary in the new version of `NextJS` with the `jsconfig.json` file that we have

2020-10-01 21:22 UTC, markrawls commented on frontend/jest.config.js
> +// For a detailed explanation regarding each configuration property, visit:
In my opinion we should, but I am not inherently correct

2020-10-06 03:11 UTC, markrawls approved these changes

2020-10-06 03:52 UTC, merged