Nav Metlife Logo leads to home queryparam
MetLifeLegalPlans/portunus pull request #215
Opened 2020-09-29 16:52 UTC by marco-wong-1

closes #166 after implementing query param on members.
Users shouldn't be able to get to portunus without coming from members (or future apps) but in case that happens the logo would link to home of portunus. (not sure if I need to account for this)

2020-09-29 17:20 UTC, Ian-MacLeod requested changes
This looks good, but we should validate the content of the home query parameter to make sure that it is a legalplans.com subdomain.

2020-09-30 21:57 UTC, marco-wong-1 commented
so I'm not too familiar with how we structure the domains, but I just used a regex to make sure it contains one legalplans.com in there. @Ian-MacLeod if you want to take another look 😃

2020-10-01 16:42 UTC, Ian-MacLeod requested changes

2020-10-01 16:42 UTC, Ian-MacLeod commented on frontend/components/Nav.js
> +    }
I think that using the URL interface to grab the host name would be a bit nicer. Also, we should also not allow things like `notlegalplans.com`. Something like this would work:

```
const hostName = new URL(home).hostname;
if (hostName.endsWith('.legalplans.com')) {
```

2020-10-01 17:18 UTC, marco-wong-1 commented
Forgot to checkout to a new branch so closing this

2020-10-01 17:18 UTC, closed without merging