BACKEND: add email search API endpoint
MetLifeLegalPlans/portunus pull request #225
Opened 2020-10-12 17:17 UTC by kborer

closes #182

2020-10-14 19:31 UTC, cviveiro commented on backend/authentication/tests/views/test_views.py
> +    def test_search_email(self, from_email, partial_email):
i find these vars to be confusingly named. Would rather `partial_email` -> something like `use_partial_email`. Not sure about a better name for `from_email`. `use_search_arg` but that's a bit bleh.

2020-10-14 19:35 UTC, hpetrow commented on backend/authentication/views.py
> +class SearchUsersView(ListAPIView):
Not sure about this, but couldn't this be part of  `ListCreateUsersView`, since I think `ListCreateAPIView` handles list api view?

2020-10-15 13:09 UTC, kborer commented on backend/authentication/tests/views/test_views.py
> +    def test_search_email(self, from_email, partial_email):
agreed, updated

2020-10-15 13:09 UTC, kborer commented on backend/authentication/views.py
> +class SearchUsersView(ListAPIView):
I didn't do that because it uses a different queryset

2020-10-15 20:04 UTC, Ian-MacLeod requested changes
Looks good. We may want to consider placing a limit on the number of results.

2020-10-15 20:04 UTC, Ian-MacLeod commented on backend/authentication/views.py
> +        search = self.request.GET.get("search")
I think `request.query_params` is slightly preferable to `request.GET`

2020-10-16 12:15 UTC, kborer commented
Thanks, I've implemented your suggestions and also added a minimum length for the search string.

2020-10-30 19:19 UTC, cviveiro approved these changes
LGTM, not sure if Heather or Ian have more to say

2020-10-30 22:07 UTC, merged