BACKEND: Add delete user API endpoint
MetLifeLegalPlans/portunus pull request #232
Opened 2020-10-19 21:48 UTC by pbirl

Closes#183

2020-10-19 22:31 UTC, Ian-MacLeod requested changes
Looks good, one linting error - we should get pre-commit set up in your environment so the linter will automatically run, but in the meantime I left a comment that should fix the error.

There is a separate commit here from your minimum password length PR - rebasing this branch off of the latest version of `develop` should fix that.

2020-10-19 22:31 UTC, Ian-MacLeod commented on backend/authentication/factories.py
> +class SuperuserFactory (UserFactory):
Code style change: remove the space between `SuperuserFactory` and the `(`

2020-10-20 17:07 UTC, cviveiro commented on backend/authentication/tests/views/test_views.py
> +        self.check_user(superuser)
this isn't related to the changes this PR makes, but i wish `check_user` was named a bit more descriptively, so that it's clear what it's doing. maybe more like `check_user_actions`?

2020-10-20 17:07 UTC, cviveiro commented on backend/authentication/factories.py
> +class SuperuserFactory(UserFactory):
Nit: I'd prefer this `SuperUser` instead of `Superuser`, and same throughout, to match more with the `StaffUser`

2020-10-20 17:07 UTC, cviveiro commented on backend/shared/permissions.py
> +class IsSameUserOrSuperuser(permissions.BasePermission):
Same comment here re: `SuperUser`

2020-10-20 18:27 UTC, cviveiro commented
Also, we're trying to start being better about adding in descriptions for what a PR does. I can add it in when merging, but it's good practice to go further than just saying what issue is closed by it and describing what it does. You can do something like this for this one:
```
This tightens the permissions on the delete user endpoint to be superuser rather than all staff.
```
Simple but will let non-engineers know exactly what changed.

2020-10-20 18:36 UTC, Ian-MacLeod commented on backend/authentication/factories.py
> +class SuperuserFactory(UserFactory):
I suggested this capitalization while we were pairing to be more consistent with the `is_superuser` field name (I think superuser is usually one word, too?) - I don't feel too strongly either way, though.

2020-10-20 18:42 UTC, cviveiro commented on backend/authentication/factories.py
> +class SuperuserFactory(UserFactory):
Meh then don't worry about changing it I also don't feel strongly

2020-10-22 16:58 UTC, Ian-MacLeod commented
Looks good, but the commit history is a little funky now - also needs to be brought up to date with `develop`. Let me know if you need help with this.

2020-11-05 16:26 UTC, cviveiro approved these changes

2020-11-10 21:32 UTC, cviveiro approved these changes

2020-11-10 22:12 UTC, merged