FRONTEND: add welcome banner for login and registration
MetLifeLegalPlans/portunus pull request #235
Opened 2020-10-24 02:21 UTC by JCog

closes #231

2020-10-26 21:26 UTC, markrawls requested changes

2020-10-26 21:26 UTC, markrawls commented on frontend/components/Layout.js
>  import MlpLogo from 'assets/images/mlp-logo.svg';
I know it wasn't added in this PR, but this needs to be migrated to a URL path instead of an import.

2020-10-26 21:26 UTC, markrawls commented on frontend/components/ExperienceModal.js
> +    zIndex: 1299,
The MUI theme has some `zIndex` constants you'll wanna look at.

https://material-ui.com/customization/default-theme/#default-theme

2020-10-26 21:48 UTC, Ian-MacLeod requested changes
Looking good overall

2020-10-26 21:48 UTC, Ian-MacLeod commented on frontend/components/ExperienceModal.js
> +    <div className={classes.fuzz}>
Is the default backdrop color ( rgba(244, 245, 247, 0.64) ) from wui not good here? I would have thought we could eliminate this wrapper and control the modal hiding/showing with the just the open prop.

2020-10-26 21:48 UTC, Ian-MacLeod commented on frontend/components/ExperienceBanner.js
> +        </Typography>
It would be better for a11y if this were a button or anchor tag.

2020-10-27 21:08 UTC, Ian-MacLeod approved these changes
Lgtm

2020-10-27 21:38 UTC, merged