BACKEND: Prep for ECS migration
MetLifeLegalPlans/portunus pull request #243
Opened 2020-12-08 23:05 UTC by markrawls

# DO NOT MERGE THIS YET, IT WILL BREAK MOST THINGS

## It is ready for review though, so do that please

Sets a good production Dockerfile, updates the dependencies, implements Celery (without need of a separate container in prod), and moves our singular task over to a Celery `shared_task`.

2020-12-08 23:35 UTC, Ian-MacLeod requested changes
Looks good in general.

This includes a zg update, right? I think it's nicest if we can put the results of that in their own commit for clarity.

2020-12-08 23:35 UTC, Ian-MacLeod commented on frontend/zg_utils/google-analytics.js
> +import GOOGLE_ANALYTICS_ID from 'utils/constants/google';
Is this right? I think it would still need to be destructured.

2020-12-08 23:35 UTC, Ian-MacLeod commented on docker-compose.yml
> +    build: &id001
Could use some more descriptive names for these anchors.

2020-12-08 23:36 UTC, markrawls commented on frontend/zg_utils/google-analytics.js
> +import GOOGLE_ANALYTICS_ID from 'utils/constants/google';
Yep, that is correct

2020-12-08 23:37 UTC, markrawls commented on docker-compose.yml
> +    build: &id001
This is what Prettier generated for them in the pre-commit hook, didn't catch those at first

2020-12-09 02:30 UTC, ambikads commented on backend/Dockerfile
> +FROM python:latest
I am not so sure if we want this, at least not until we get to practice "build once, deploy many" approach.

2020-12-09 02:36 UTC, ambikads commented on backend/Dockerfile.local
> +CMD ./manage.py wait_for_db && ./manage.py migrate && ./manage.py createcachetable && uvicorn --host 0.0.0.0 --port 3001 --reload backend.asgi:application
naive question, does celery not work for local development and testing?

2020-12-09 04:20 UTC, markrawls commented on backend/Dockerfile.local
> +CMD ./manage.py wait_for_db && ./manage.py migrate && ./manage.py createcachetable && uvicorn --host 0.0.0.0 --port 3001 --reload backend.asgi:application
It does! We're running it in a separate instance of the backend container though, so it reloads every time we make a change. The production daemon runs in the same container but does not provide reloading.

2020-12-09 04:21 UTC, markrawls commented on backend/Dockerfile
> +FROM python:latest
Wouldn't that be what we're moving to with the backend on ECS?

2020-12-09 04:26 UTC, ambikads commented on backend/Dockerfile
> +FROM python:latest
It wouldn't. We will need to change the way we deploy to production. Once the images are built for testing, the same image should be deployed to production. Right now we build every time.

2020-12-09 16:31 UTC, markrawls commented on backend/Dockerfile
> +FROM python:latest
Ah, noted. I'll pin it at 3.9 for now.

2020-12-09 17:11 UTC, markrawls commented
> This includes a zg update, right? I think it's nicest if we can put the results of that in their own commit for clarity.

That was only dependency updates, and splitting those out manually is a touch difficult. For the time being I'm gonna opt to leave em in one commit.

2020-12-10 19:45 UTC, Ian-MacLeod commented
> That was only dependency updates, and splitting those out manually is a touch difficult. For the time being I'm gonna opt to leave em in one commit.

It's OK to leave it in here since they are already mixed, but in the future I think a separate commit makes sense. In particular, it helps grokking what is included when looking at the commits in a RC.

2020-12-10 19:48 UTC, Ian-MacLeod requested changes

2020-12-10 19:48 UTC, Ian-MacLeod commented on frontend/public/browserCompatibility.js
> +/* eslint-disable */
Did this sneak in here somehow? It's not needed, right?

2020-12-10 22:30 UTC, markrawls commented on frontend/public/browserCompatibility.js
> +/* eslint-disable */
I put that in there because the linter wanted it moved to ES6 standards and this file doesn't get transpiled.

2021-01-13 18:49 UTC, Ian-MacLeod approved these changes
This looks good to me

2021-01-13 21:17 UTC, markrawls commented
Excellent, I'm going to get this merged shortly and work on moving over some lower environments.

2021-01-13 21:50 UTC, ambikads commented
fine with me too. When ready, lets merge to develop and fix the CI/CD and deploy to dev before proceeding with other lower environments(qa and test). Please remember to treat staging similar to production as we have some sponsors using testing for various tests.

2021-01-13 22:34 UTC, merged